### ISSUE TITLE
Add support for Wallust :pleading_face: 

### ISSUE THREAD

**Issue by xNyxion** [danihek/Themecord#2]
Hey dude, would love to use that :D 

but could you add support for wallust? pywal is no longer maintained... :sob:

**Comment by danihek** [comment]
Hello, thanks for opening the issue and great idea btw.

I implemented that in c2ef410b65961dfd975ad4165d266519afc37352, but colors are a bit off, so I'll have to play with values for some time to set it properly.

If you have any other ideas or you see something open new issue. 
I'm closing this as completed, Thanks.
